# Generated by Django 4.2.3 on 2023-08-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="food_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_name", models.CharField(max_length=30)),
                ("rating", models.CharField(max_length=30)),
                ("item", models.CharField(max_length=10)),
                ("price", models.CharField(max_length=10)),
                ("contact", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=30)),
            ],
        ),
    ]
